wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: lightgbm
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717190054.0
    t:
      1:
      - 1
      - 4
      - 5
      - 6
      - 7
      - 8
      - 11
      - 15
      - 49
      - 53
      - 55
      - 105
      2:
      - 1
      - 4
      - 5
      - 6
      - 7
      - 8
      - 11
      - 15
      - 49
      - 53
      - 55
      - 105
      3:
      - 23
      4: 3.10.14
      5: 0.16.6
      6: 4.38.2
      8:
      - 3
      - 5
      13: windows-amd64
